# Generated by Django 5.0.6 on 2025-09-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_household_options_alter_householduser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('currency', models.CharField(default='PEN', max_length=8)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField()),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.household')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.tariff')),
            ],
            options={
                'ordering': ['-assigned_from'],
                'unique_together': {('household', 'assigned_from')},
            },
        ),
    ]
