# Generated by Django 5.0.6 on 2025-09-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('model', models.CharField(max_length=60)),
                ('fw_version', models.CharField(max_length=30)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('device_capabilities', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='core.household')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('flow_lpm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pressure_kpa', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volume_liters_delta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('temp_c', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', '-ts'], name='idx_readings_device_ts_desc')],
                'unique_together': {('device', 'ts')},
            },
        ),
    ]
