# Generated by Django 5.0.6 on 2025-09-29 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='householduser',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RemoveField(
            model_name='household',
            name='region',
        ),
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='household',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='household',
            name='country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='household',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='timezone',
            field=models.CharField(default='America/Lima', max_length=64),
        ),
        migrations.AlterField(
            model_name='householduser',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.household'),
        ),
        migrations.AlterField(
            model_name='householduser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer')], max_length=12),
        ),
        migrations.AlterField(
            model_name='householduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to=settings.AUTH_USER_MODEL),
        ),
    ]
