# Generated by Django 5.0.6 on 2025-09-29 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], max_length=10)),
                ('target_liters', models.DecimalField(decimal_places=3, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.household')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
